name: "Build Mako"
description: "Checkout, and build"

inputs:
  repository:
    description: "The mako repository to use"
    required: true
    default: "umijs/mako"
  path:
    description: "Destination path to the mako repository"
    required: true
    default: ".mako"
  ref:
    description: "The branch, tag or SHA to checkout"
    required: true
    default: "master"
  node-version:
    description: "The version of Node.js to set up"
    required: true
    default: "20"

outputs:
  artifact-name:
    description: "The name of the uploaded artifact"

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        npm install -g corepack@0.24.1
        echo "Corepack version: $(corepack --version)"
        corepack enable
    - shell: bash
      run: pnpm --version
    - shell: bash
      run: pnpm install --prefer-frozen-lockfile --prefer-offline
    - name: Build Mako JS
      shell: bash
      run: >-
        node bin/cli.js build
        --repository ${{ inputs.repository }}
        --ref ${{ inputs.ref }}
    - uses: actions/download-artifact@v4
      with:
        name: binding-linux-x64-gnu
        path: ${{ inputs.path }}/crates/binding
    - name: Show restored binding
      shell: bash
      run: ls -lah ${{ inputs.path }}/crates/binding/*.node
